// Países del mundo (en español) con su código ISO-2, capital y, para los
// mercados principales, sus ciudades. Preparado para el filtrado por país/ciudad
// en "Descubrir barberías".
export type Country = {
  name: string;
  code: string; // ISO 3166-1 alfa-2 (para derivar la bandera)
  capital: string;
  cities?: string[];
};

// Bandera emoji a partir del código ISO-2 (indicadores regionales unicode).
export function flagEmoji(code: string): string {
  return code
    .toUpperCase()
    .replace(/./g, (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)));
}

export const COUNTRIES: Country[] = [
  { name: "Afganistán", code: "AF", capital: "Kabul" },
  { name: "Albania", code: "AL", capital: "Tirana" },
  { name: "Alemania", code: "DE", capital: "Berlín" },
  { name: "Andorra", code: "AD", capital: "Andorra la Vieja" },
  { name: "Angola", code: "AO", capital: "Luanda" },
  { name: "Antigua y Barbuda", code: "AG", capital: "Saint John's" },
  { name: "Arabia Saudita", code: "SA", capital: "Riad" },
  { name: "Argelia", code: "DZ", capital: "Argel" },
  {
    name: "Argentina",
    code: "AR",
    capital: "Buenos Aires",
    cities: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "San Miguel de Tucumán", "Mar del Plata", "Salta"],
  },
  { name: "Armenia", code: "AM", capital: "Ereván" },
  { name: "Australia", code: "AU", capital: "Canberra" },
  { name: "Austria", code: "AT", capital: "Viena" },
  { name: "Azerbaiyán", code: "AZ", capital: "Bakú" },
  { name: "Bahamas", code: "BS", capital: "Nasáu" },
  { name: "Bangladés", code: "BD", capital: "Daca" },
  { name: "Barbados", code: "BB", capital: "Bridgetown" },
  { name: "Baréin", code: "BH", capital: "Manama" },
  { name: "Bélgica", code: "BE", capital: "Bruselas" },
  { name: "Belice", code: "BZ", capital: "Belmopán" },
  { name: "Benín", code: "BJ", capital: "Porto Novo" },
  { name: "Bielorrusia", code: "BY", capital: "Minsk" },
  { name: "Birmania", code: "MM", capital: "Naipyidó" },
  {
    name: "Bolivia",
    code: "BO",
    capital: "La Paz",
    cities: ["La Paz", "Santa Cruz de la Sierra", "Cochabamba", "Sucre", "Oruro", "Tarija", "Potosí", "El Alto"],
  },
  { name: "Bosnia y Herzegovina", code: "BA", capital: "Sarajevo" },
  { name: "Botsuana", code: "BW", capital: "Gaborone" },
  {
    name: "Brasil",
    code: "BR",
    capital: "Brasilia",
    cities: ["Brasilia", "São Paulo", "Río de Janeiro", "Salvador", "Fortaleza", "Belo Horizonte", "Curitiba", "Manaos"],
  },
  { name: "Brunéi", code: "BN", capital: "Bandar Seri Begawan" },
  { name: "Bulgaria", code: "BG", capital: "Sofía" },
  { name: "Burkina Faso", code: "BF", capital: "Uagadugú" },
  { name: "Burundi", code: "BI", capital: "Buyumbura" },
  { name: "Bután", code: "BT", capital: "Timbu" },
  { name: "Cabo Verde", code: "CV", capital: "Praia" },
  { name: "Camboya", code: "KH", capital: "Nom Pen" },
  { name: "Camerún", code: "CM", capital: "Yaundé" },
  { name: "Canadá", code: "CA", capital: "Ottawa", cities: ["Ottawa", "Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Quebec"] },
  { name: "Catar", code: "QA", capital: "Doha" },
  { name: "Chad", code: "TD", capital: "Yamena" },
  {
    name: "Chile",
    code: "CL",
    capital: "Santiago",
    cities: ["Santiago", "Valparaíso", "Concepción", "Antofagasta", "Viña del Mar", "Temuco", "La Serena", "Iquique"],
  },
  { name: "China", code: "CN", capital: "Pekín" },
  { name: "Chipre", code: "CY", capital: "Nicosia" },
  { name: "Ciudad del Vaticano", code: "VA", capital: "Ciudad del Vaticano" },
  {
    name: "Colombia",
    code: "CO",
    capital: "Bogotá",
    cities: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bucaramanga", "Pereira"],
  },
  { name: "Comoras", code: "KM", capital: "Moroni" },
  { name: "Corea del Norte", code: "KP", capital: "Pionyang" },
  { name: "Corea del Sur", code: "KR", capital: "Seúl" },
  { name: "Costa de Marfil", code: "CI", capital: "Yamusukro" },
  { name: "Costa Rica", code: "CR", capital: "San José", cities: ["San José", "Alajuela", "Cartago", "Heredia", "Liberia", "Puntarenas"] },
  { name: "Croacia", code: "HR", capital: "Zagreb" },
  { name: "Cuba", code: "CU", capital: "La Habana", cities: ["La Habana", "Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara"] },
  { name: "Dinamarca", code: "DK", capital: "Copenhague" },
  { name: "Dominica", code: "DM", capital: "Roseau" },
  {
    name: "Ecuador",
    code: "EC",
    capital: "Quito",
    cities: ["Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Machala", "Manta", "Ambato", "Loja"],
  },
  { name: "Egipto", code: "EG", capital: "El Cairo" },
  { name: "El Salvador", code: "SV", capital: "San Salvador", cities: ["San Salvador", "Santa Ana", "San Miguel", "Soyapango"] },
  { name: "Emiratos Árabes Unidos", code: "AE", capital: "Abu Dabi", cities: ["Abu Dabi", "Dubái", "Sharjah", "Al Ain"] },
  { name: "Eritrea", code: "ER", capital: "Asmara" },
  { name: "Eslovaquia", code: "SK", capital: "Bratislava" },
  { name: "Eslovenia", code: "SI", capital: "Liubliana" },
  {
    name: "España",
    code: "ES",
    capital: "Madrid",
    cities: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Zaragoza", "Málaga", "Bilbao", "Murcia"],
  },
  {
    name: "Estados Unidos",
    code: "US",
    capital: "Washington D. C.",
    cities: ["Nueva York", "Los Ángeles", "Chicago", "Houston", "Miami", "Phoenix", "Filadelfia", "Washington D. C."],
  },
  { name: "Estonia", code: "EE", capital: "Tallin" },
  { name: "Esuatini", code: "SZ", capital: "Mbabane" },
  { name: "Etiopía", code: "ET", capital: "Adís Abeba" },
  { name: "Filipinas", code: "PH", capital: "Manila" },
  { name: "Finlandia", code: "FI", capital: "Helsinki" },
  { name: "Fiyi", code: "FJ", capital: "Suva" },
  { name: "Francia", code: "FR", capital: "París", cities: ["París", "Marsella", "Lyon", "Toulouse", "Niza", "Nantes", "Burdeos"] },
  { name: "Gabón", code: "GA", capital: "Libreville" },
  { name: "Gambia", code: "GM", capital: "Banjul" },
  { name: "Georgia", code: "GE", capital: "Tiflis" },
  { name: "Ghana", code: "GH", capital: "Acra" },
  { name: "Granada", code: "GD", capital: "Saint George's" },
  { name: "Grecia", code: "GR", capital: "Atenas" },
  { name: "Guatemala", code: "GT", capital: "Ciudad de Guatemala", cities: ["Ciudad de Guatemala", "Quetzaltenango", "Escuintla", "Mixco"] },
  { name: "Guyana", code: "GY", capital: "Georgetown" },
  { name: "Guinea", code: "GN", capital: "Conakri" },
  { name: "Guinea-Bisáu", code: "GW", capital: "Bisáu" },
  { name: "Guinea Ecuatorial", code: "GQ", capital: "Malabo" },
  { name: "Haití", code: "HT", capital: "Puerto Príncipe" },
  { name: "Honduras", code: "HN", capital: "Tegucigalpa", cities: ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba"] },
  { name: "Hungría", code: "HU", capital: "Budapest" },
  { name: "India", code: "IN", capital: "Nueva Delhi" },
  { name: "Indonesia", code: "ID", capital: "Yakarta" },
  { name: "Irak", code: "IQ", capital: "Bagdad" },
  { name: "Irán", code: "IR", capital: "Teherán" },
  { name: "Irlanda", code: "IE", capital: "Dublín" },
  { name: "Islandia", code: "IS", capital: "Reikiavik" },
  { name: "Islas Marshall", code: "MH", capital: "Majuro" },
  { name: "Islas Salomón", code: "SB", capital: "Honiara" },
  { name: "Israel", code: "IL", capital: "Jerusalén" },
  { name: "Italia", code: "IT", capital: "Roma", cities: ["Roma", "Milán", "Nápoles", "Turín", "Palermo", "Génova", "Florencia"] },
  { name: "Jamaica", code: "JM", capital: "Kingston" },
  { name: "Japón", code: "JP", capital: "Tokio" },
  { name: "Jordania", code: "JO", capital: "Amán" },
  { name: "Kazajistán", code: "KZ", capital: "Astaná" },
  { name: "Kenia", code: "KE", capital: "Nairobi" },
  { name: "Kirguistán", code: "KG", capital: "Biskek" },
  { name: "Kiribati", code: "KI", capital: "Tarawa Sur" },
  { name: "Kuwait", code: "KW", capital: "Kuwait" },
  { name: "Laos", code: "LA", capital: "Vientián" },
  { name: "Lesoto", code: "LS", capital: "Maseru" },
  { name: "Letonia", code: "LV", capital: "Riga" },
  { name: "Líbano", code: "LB", capital: "Beirut" },
  { name: "Liberia", code: "LR", capital: "Monrovia" },
  { name: "Libia", code: "LY", capital: "Trípoli" },
  { name: "Liechtenstein", code: "LI", capital: "Vaduz" },
  { name: "Lituania", code: "LT", capital: "Vilna" },
  { name: "Luxemburgo", code: "LU", capital: "Luxemburgo" },
  { name: "Macedonia del Norte", code: "MK", capital: "Skopie" },
  { name: "Madagascar", code: "MG", capital: "Antananarivo" },
  { name: "Malasia", code: "MY", capital: "Kuala Lumpur" },
  { name: "Malaui", code: "MW", capital: "Lilongüe" },
  { name: "Maldivas", code: "MV", capital: "Malé" },
  { name: "Malí", code: "ML", capital: "Bamako" },
  { name: "Malta", code: "MT", capital: "La Valeta" },
  { name: "Marruecos", code: "MA", capital: "Rabat" },
  { name: "Mauricio", code: "MU", capital: "Port Louis" },
  { name: "Mauritania", code: "MR", capital: "Nuakchot" },
  {
    name: "México",
    code: "MX",
    capital: "Ciudad de México",
    cities: ["Ciudad de México", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Cancún", "Mérida"],
  },
  { name: "Micronesia", code: "FM", capital: "Palikir" },
  { name: "Moldavia", code: "MD", capital: "Chisináu" },
  { name: "Mónaco", code: "MC", capital: "Mónaco" },
  { name: "Mongolia", code: "MN", capital: "Ulán Bator" },
  { name: "Montenegro", code: "ME", capital: "Podgorica" },
  { name: "Mozambique", code: "MZ", capital: "Maputo" },
  { name: "Namibia", code: "NA", capital: "Windhoek" },
  { name: "Nauru", code: "NR", capital: "Yaren" },
  { name: "Nepal", code: "NP", capital: "Katmandú" },
  { name: "Nicaragua", code: "NI", capital: "Managua", cities: ["Managua", "León", "Masaya", "Granada", "Chinandega"] },
  { name: "Níger", code: "NE", capital: "Niamey" },
  { name: "Nigeria", code: "NG", capital: "Abuya" },
  { name: "Noruega", code: "NO", capital: "Oslo" },
  { name: "Nueva Zelanda", code: "NZ", capital: "Wellington" },
  { name: "Omán", code: "OM", capital: "Mascate" },
  { name: "Países Bajos", code: "NL", capital: "Ámsterdam" },
  { name: "Pakistán", code: "PK", capital: "Islamabad" },
  { name: "Palaos", code: "PW", capital: "Ngerulmud" },
  { name: "Palestina", code: "PS", capital: "Ramala" },
  { name: "Panamá", code: "PA", capital: "Ciudad de Panamá", cities: ["Ciudad de Panamá", "Colón", "David", "La Chorrera"] },
  { name: "Papúa Nueva Guinea", code: "PG", capital: "Puerto Moresby" },
  { name: "Paraguay", code: "PY", capital: "Asunción", cities: ["Asunción", "Ciudad del Este", "San Lorenzo", "Luque", "Encarnación"] },
  {
    name: "Perú",
    code: "PE",
    capital: "Lima",
    cities: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Cusco", "Huancayo", "Iquitos", "Tacna", "Callao", "Chimbote", "Juliaca", "Ica", "Pucallpa", "Cajamarca", "Puno"],
  },
  { name: "Polonia", code: "PL", capital: "Varsovia" },
  { name: "Portugal", code: "PT", capital: "Lisboa", cities: ["Lisboa", "Oporto", "Braga", "Coímbra", "Faro", "Funchal"] },
  { name: "Reino Unido", code: "GB", capital: "Londres", cities: ["Londres", "Mánchester", "Birmingham", "Liverpool", "Glasgow", "Edimburgo"] },
  { name: "República Centroafricana", code: "CF", capital: "Bangui" },
  { name: "República Checa", code: "CZ", capital: "Praga" },
  { name: "República del Congo", code: "CG", capital: "Brazzaville" },
  { name: "República Democrática del Congo", code: "CD", capital: "Kinsasa" },
  {
    name: "República Dominicana",
    code: "DO",
    capital: "Santo Domingo",
    cities: ["Santo Domingo", "Santiago de los Caballeros", "La Romana", "San Pedro de Macorís", "Punta Cana"],
  },
  { name: "Ruanda", code: "RW", capital: "Kigali" },
  { name: "Rumanía", code: "RO", capital: "Bucarest" },
  { name: "Rusia", code: "RU", capital: "Moscú" },
  { name: "Samoa", code: "WS", capital: "Apia" },
  { name: "San Cristóbal y Nieves", code: "KN", capital: "Basseterre" },
  { name: "San Marino", code: "SM", capital: "San Marino" },
  { name: "San Vicente y las Granadinas", code: "VC", capital: "Kingstown" },
  { name: "Santa Lucía", code: "LC", capital: "Castries" },
  { name: "Santo Tomé y Príncipe", code: "ST", capital: "Santo Tomé" },
  { name: "Senegal", code: "SN", capital: "Dakar" },
  { name: "Serbia", code: "RS", capital: "Belgrado" },
  { name: "Seychelles", code: "SC", capital: "Victoria" },
  { name: "Sierra Leona", code: "SL", capital: "Freetown" },
  { name: "Singapur", code: "SG", capital: "Singapur" },
  { name: "Siria", code: "SY", capital: "Damasco" },
  { name: "Somalia", code: "SO", capital: "Mogadiscio" },
  { name: "Sri Lanka", code: "LK", capital: "Colombo" },
  { name: "Sudáfrica", code: "ZA", capital: "Pretoria" },
  { name: "Sudán", code: "SD", capital: "Jartum" },
  { name: "Sudán del Sur", code: "SS", capital: "Yuba" },
  { name: "Suecia", code: "SE", capital: "Estocolmo" },
  { name: "Suiza", code: "CH", capital: "Berna" },
  { name: "Surinam", code: "SR", capital: "Paramaribo" },
  { name: "Tailandia", code: "TH", capital: "Bangkok" },
  { name: "Tanzania", code: "TZ", capital: "Dodoma" },
  { name: "Tayikistán", code: "TJ", capital: "Dusambé" },
  { name: "Timor Oriental", code: "TL", capital: "Dili" },
  { name: "Togo", code: "TG", capital: "Lomé" },
  { name: "Tonga", code: "TO", capital: "Nukualofa" },
  { name: "Trinidad y Tobago", code: "TT", capital: "Puerto España" },
  { name: "Túnez", code: "TN", capital: "Túnez" },
  { name: "Turkmenistán", code: "TM", capital: "Asjabad" },
  { name: "Turquía", code: "TR", capital: "Ankara" },
  { name: "Tuvalu", code: "TV", capital: "Funafuti" },
  { name: "Ucrania", code: "UA", capital: "Kiev" },
  { name: "Uganda", code: "UG", capital: "Kampala" },
  { name: "Uruguay", code: "UY", capital: "Montevideo", cities: ["Montevideo", "Salto", "Ciudad de la Costa", "Paysandú", "Las Piedras"] },
  { name: "Uzbekistán", code: "UZ", capital: "Taskent" },
  { name: "Vanuatu", code: "VU", capital: "Port Vila" },
  {
    name: "Venezuela",
    code: "VE",
    capital: "Caracas",
    cities: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Ciudad Guayana", "Maturín"],
  },
  { name: "Vietnam", code: "VN", capital: "Hanói" },
  { name: "Yemen", code: "YE", capital: "Saná" },
  { name: "Yibuti", code: "DJ", capital: "Yibuti" },
  { name: "Zambia", code: "ZM", capital: "Lusaka" },
  { name: "Zimbabue", code: "ZW", capital: "Harare" },
];

export const countryByName = (name: string): Country | undefined =>
  COUNTRIES.find((c) => c.name === name);

// Códigos telefónicos (prefijo internacional) por código ISO-2.
export const DIAL_CODES: Record<string, string> = {
  AF: "+93", AL: "+355", DE: "+49", AD: "+376", AO: "+244", AG: "+1", SA: "+966",
  DZ: "+213", AR: "+54", AM: "+374", AU: "+61", AT: "+43", AZ: "+994", BS: "+1",
  BD: "+880", BB: "+1", BH: "+973", BE: "+32", BZ: "+501", BJ: "+229", BY: "+375",
  MM: "+95", BO: "+591", BA: "+387", BW: "+267", BR: "+55", BN: "+673", BG: "+359",
  BF: "+226", BI: "+257", BT: "+975", CV: "+238", KH: "+855", CM: "+237", CA: "+1",
  QA: "+974", TD: "+235", CL: "+56", CN: "+86", CY: "+357", VA: "+39", CO: "+57",
  KM: "+269", KP: "+850", KR: "+82", CI: "+225", CR: "+506", HR: "+385", CU: "+53",
  DK: "+45", DM: "+1", EC: "+593", EG: "+20", SV: "+503", AE: "+971", ER: "+291",
  SK: "+421", SI: "+386", ES: "+34", US: "+1", EE: "+372", SZ: "+268", ET: "+251",
  PH: "+63", FI: "+358", FJ: "+679", FR: "+33", GA: "+241", GM: "+220", GE: "+995",
  GH: "+233", GD: "+1", GR: "+30", GT: "+502", GY: "+592", GN: "+224", GW: "+245",
  GQ: "+240", HT: "+509", HN: "+504", HU: "+36", IN: "+91", ID: "+62", IQ: "+964",
  IR: "+98", IE: "+353", IS: "+354", MH: "+692", SB: "+677", IL: "+972", IT: "+39",
  JM: "+1", JP: "+81", JO: "+962", KZ: "+7", KE: "+254", KG: "+996", KI: "+686",
  KW: "+965", LA: "+856", LS: "+266", LV: "+371", LB: "+961", LR: "+231", LY: "+218",
  LI: "+423", LT: "+370", LU: "+352", MK: "+389", MG: "+261", MY: "+60", MW: "+265",
  MV: "+960", ML: "+223", MT: "+356", MA: "+212", MU: "+230", MR: "+222", MX: "+52",
  FM: "+691", MD: "+373", MC: "+377", MN: "+976", ME: "+382", MZ: "+258", NA: "+264",
  NR: "+674", NP: "+977", NI: "+505", NE: "+227", NG: "+234", NO: "+47", NZ: "+64",
  OM: "+968", NL: "+31", PK: "+92", PW: "+680", PS: "+970", PA: "+507", PG: "+675",
  PY: "+595", PE: "+51", PL: "+48", PT: "+351", GB: "+44", CF: "+236", CZ: "+420",
  CG: "+242", CD: "+243", DO: "+1", RW: "+250", RO: "+40", RU: "+7", WS: "+685",
  KN: "+1", SM: "+378", VC: "+1", LC: "+1", ST: "+239", SN: "+221", RS: "+381",
  SC: "+248", SL: "+232", SG: "+65", SY: "+963", SO: "+252", LK: "+94", ZA: "+27",
  SD: "+249", SS: "+211", SE: "+46", CH: "+41", SR: "+597", TH: "+66", TZ: "+255",
  TJ: "+992", TL: "+670", TG: "+228", TO: "+676", TT: "+1", TN: "+216", TM: "+993",
  TR: "+90", TV: "+688", UA: "+380", UG: "+256", UY: "+598", UZ: "+998", VU: "+678",
  VE: "+58", VN: "+84", YE: "+967", DJ: "+253", ZM: "+260", ZW: "+263",
};
